stages:
  convert_data:
    cmd: scripts/convert_all_data.sh
    deps:
    - data/raw/combined_data_1.txt
    - data/raw/combined_data_2.txt
    - data/raw/combined_data_3.txt
    - data/raw/combined_data_4.txt
    - scripts/convert_all_data.sh
    - scripts/convert_raw_data.py
    outs:
    - data/clean/data_1.csv
    - data/clean/data_2.csv
    - data/clean/data_3.csv
    - data/clean/data_4.csv
  split_data:
    cmd: python3 scripts/transform_split_data.py data/clean/
    deps:
    - data/clean/data_1.csv
    - data/clean/data_2.csv
    - data/clean/data_3.csv
    - data/clean/data_4.csv
    - scripts/transform_split_data.py
    params:
    - prepare.seed
    - prepare.train_split
    - prepare.val_split
    outs:
    - data/clean/test_data.csv
    - data/clean/train_data.csv
    - data/clean/val_data.csv
